import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, stat, writeFile, mkdir, symlink, lstat, rename, rm, cp, chmod, readlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import type { DesiredState, Skill } from "../shared/types.ts";
import { synchronize } from "../cli/sync.ts";
import { sameFileHashes, sameInstalledFileHashes } from "../cli/file-state.ts";

function skill(content: string, revision = "r1"): Skill {
  return {
    id: "s1",
    name: "demo",
    title: "Demo",
    description: "",
    author: "test",
    source: "test",
    kind: "custom",
    category: "Test",
    icon: "",
    color: "",
    selected: true,
    enabled: true,
    autoUpdate: true,
    revision,
    versions: [],
    files: [
      { path: "SKILL.md", content },
      { path: "scripts/run.sh", content: "#!/bin/sh\n", mode: 0o755 },
    ],
    requirements: [],
    targets: [],
    updatedAt: new Date().toISOString(),
  };
}
const desired = (s: Skill[]): DesiredState => ({
  generation: 1,
  skills: s,
  resolutions: {},
});

test("running Python skill scripts does not conflict on generated bytecode", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-python-cache-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), target = join(root, "agent");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agents, home);
  const cache = join(target, "demo/scripts/__pycache__");
  await mkdir(cache, { recursive: true });
  await writeFile(join(cache, "search.cpython-313.pyc"), Buffer.from([0, 255, 3]));
  const receipts = await synchronize(desired([skill("one")]), agents, home);
  assert.equal(receipts[0].status, "synchronized");
  assert.deepEqual(await readFile(join(cache, "search.cpython-313.pyc")), Buffer.from([0, 255, 3]));
  await writeFile(join(target, "demo/SKILL.md"), "edited instructions");
  const modified = await synchronize(desired([skill("one")]), agents, home);
  assert.equal(modified[0].status, "conflicted");
  assert.ok(modified[0].localFiles?.some(file => file.path.endsWith(".pyc")), "Full recovery snapshots still include the cache");
});

test("bundled bytecode and unexpected symlinks remain part of conflict detection", () => {
  const path = "scripts/__pycache__/search.cpython-313.pyc";
  const hash = `420:${"a".repeat(64)}`;
  assert.ok(sameInstalledFileHashes({ [path]: hash }, {}));
  assert.ok(!sameInstalledFileHashes({}, { [path]: hash }), "Deleting a bundled file still matters");
  assert.ok(!sameInstalledFileHashes({ [path]: `420:${"b".repeat(64)}` }, { [path]: hash }));
  assert.ok(!sameInstalledFileHashes({ [path]: `symlink:${"a".repeat(64)}` }, {}));
  assert.ok(!sameInstalledFileHashes({ "scripts/__pycache__/notes.md": hash }, {}));
});

test("same-content preexisting skill links ignore rw modes without altering the source", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-portable-link-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const source = join(root, "original/demo"), target = join(root, "claude"), home = join(root, "state");
  await mkdir(join(source, "scripts"), { recursive: true });
  await mkdir(target);
  await writeFile(join(source, "SKILL.md"), "one");
  await writeFile(join(source, "scripts/run.sh"), "#!/bin/sh\n");
  await chmod(join(source, "SKILL.md"), 0o664);
  await chmod(join(source, "scripts/run.sh"), 0o775);
  await symlink(source, join(target, "demo"));
  const agent = [{ id: "claude-code", path: target }];
  const receipts = await synchronize(desired([skill("one")]), agent, home);
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(receipts[0].revision, "r1");
  assert.equal(receipts[0].managed, false);
  assert.equal(await readlink(join(target, "demo")), source);
  assert.equal((await stat(join(source, "SKILL.md"))).mode & 0o777, 0o664);
  assert.equal((await stat(join(source, "scripts/run.sh"))).mode & 0o777, 0o775);
  await chmod(join(source, "SKILL.md"), 0o600);
  assert.equal((await synchronize(desired([skill("two", "r2")]), agent, home))[0].status, "synchronized");
  assert.equal(await readFile(join(source, "SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
});

test("managed skill permission changes do not block sync, update, or removal; executable edits do", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-portable-managed-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await chmod(join(target, "demo/SKILL.md"), 0o600);
  await chmod(join(target, "demo/scripts/run.sh"), 0o700);
  assert.equal((await synchronize(desired([skill("one")]), agent, home))[0].status, "synchronized");
  assert.equal((await synchronize(desired([skill("two", "r2")]), agent, home))[0].status, "synchronized");
  await chmod(join(target, "demo/scripts/run.sh"), 0o644);
  const conflicted = await synchronize(desired([skill("three", "r3")]), agent, home);
  assert.equal(conflicted[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  await chmod(join(target, "demo/scripts/run.sh"), 0o775);
  assert.equal((await synchronize(desired([]), agent, home))[0].status, "synchronized");
  assert.equal(await lstat(join(target, "demo")).catch(() => null), null);
});

test("legacy hash comparison preserves file kind and content and accounts for Windows permissions", () => {
  const digest = createHash("sha256").update("same").digest("hex");
  assert.ok(sameFileHashes({ file: `432:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(!sameFileHashes({ file: `493:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(sameFileHashes({ file: `438:${digest}` }, { file: `493:${digest}` }, "win32"));
  assert.ok(!sameFileHashes({ file: `symlink:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(!sameFileHashes({ file: `420:${digest}` }, {}, "linux"));
});

test("Equip updates observed installations through its store and preserves their original sources", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-nova-links-"));
  const target = join(root, "agent"), shared = join(root, "shared"), home = join(root, "state");
  await synchronize(desired([skill("one")]), [{ id: "codex", path: shared }], join(root, "seed"));
  await mkdir(target);
  await symlink(join(shared, "demo"), join(target, "demo"));
  const linked = skill("one");
  const receipts = await synchronize(desired([linked]), [{ id: "codex", path: target }], home);
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(receipts[0].managed, false);
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);

  const updated = skill("two", "r2");
  const updateReceipts = await synchronize(
    { ...desired([updated]), generation: 2 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(updateReceipts[0].status, "synchronized");
  assert.notEqual(updateReceipts[0].managed, false);
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  const backups = await import("node:fs/promises").then((fs) =>
    fs.readdir(join(home, "backups")),
  );
  assert.equal(backups.length, 1);
  assert.equal(
    await readFile(join(home, "backups", backups[0], "SKILL.md"), "utf8"),
    "one",
  );

  await writeFile(join(target, "demo/SKILL.md"), "local work");
  const changed = skill("three", "r3");
  const conflict = await synchronize(
    { ...desired([changed]), generation: 3 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(conflict[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local work");
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");

  const removed = await synchronize(
    { generation: 4, skills: [], resolutions: {} },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(removed[0].status, "conflicted");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local work");
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");
});

test("identical revision synchronizes to two isolated devices", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  const a = join(root, "a");
  const b = join(root, "b");
  const receipts = await synchronize(
    desired([skill("one")]),
    [
      { id: "codex", path: a },
      { id: "claude-code", path: b },
    ],
    home,
  );
  assert.deepEqual(
    receipts.map((r) => r.status),
    ["synchronized", "synchronized"],
  );
  assert.equal(await readFile(join(a, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(b, "demo/SKILL.md"), "utf8"), "one");
  assert.equal((await lstat(join(a, "demo"))).isSymbolicLink(), true);
  assert.equal((await lstat(join(b, "demo"))).isSymbolicLink(), true);
  const fs = await import("node:fs/promises");
  assert.equal(
    await fs.realpath(join(a, "demo")),
    await fs.realpath(join(home, "skills/demo")),
  );
  assert.equal(
    await fs.realpath(join(b, "demo")),
    await fs.realpath(join(home, "skills/demo")),
  );
});

test("a clean legacy managed directory migrates to the canonical link", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-migrate-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(target, "demo/scripts"), { recursive: true });
  await writeFile(join(target, "demo/SKILL.md"), "one");
  await writeFile(join(target, "demo/scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  const hashes = {
    "SKILL.md": `${0o644}:${createHash("sha256").update("one").digest("hex")}`,
    "scripts/run.sh": `${0o755}:${createHash("sha256").update("#!/bin/sh\n").digest("hex")}`,
  };
  await mkdir(home);
  await writeFile(join(home, "ledger.json"), JSON.stringify({ generation: 1, installs: {
    "s1:codex::": { skillId: "s1", agent: "codex", revision: "r1", files: hashes, path: join(target, "demo") },
  } }));
  const receipts = await synchronize(desired([skill("one")]), [{ id: "codex", path: target }], home);
  assert.equal(receipts[0].status, "synchronized");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "one");
});

test("local edits conflict and preserve the last good install", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const receipts = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2 },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
});

test("first connect preserves a same-name local skill when no baseline is known", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-unknown-base-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(target, "demo/scripts"), { recursive: true });
  await writeFile(join(target, "demo/SKILL.md"), "edited before Equip");
  await writeFile(join(target, "demo/scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });

  const receipts = await synchronize(
    desired([skill("dashboard")]),
    [{ id: "codex", path: target }],
    home,
  );

  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].revision, "");
  assert.equal(
    receipts[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "edited before Equip",
  );
  assert.equal(
    await readFile(join(target, "demo/SKILL.md"), "utf8"),
    "edited before Equip",
  );
  assert.equal(
    await readFile(join(home, "skills/demo/SKILL.md"), "utf8"),
    "dashboard",
  );
});

test("replacing an unknown-base canonical conflict keeps a recovery copy", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-canonical-recovery-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(home, "skills/demo/scripts"), { recursive: true });
  await writeFile(join(home, "skills/demo/SKILL.md"), "unknown local work");
  await writeFile(join(home, "skills/demo/scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });

  const conflict = await synchronize(
    desired([skill("dashboard")]),
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(conflict[0].status, "conflicted");
  assert.equal(
    await readFile(join(home, "skills/demo/SKILL.md"), "utf8"),
    "unknown local work",
  );

  const replaced = await synchronize(
    {
      ...desired([skill("dashboard")]),
      generation: 2,
      resolutions: { "s1:codex::": "replace" },
    },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.equal(
    await readFile(join(target, "demo/SKILL.md"), "utf8"),
    "dashboard",
  );
  const backups = await import("node:fs/promises").then((fs) =>
    fs.readdir(join(home, "backups")),
  );
  assert.equal(backups.length, 1);
  assert.equal(
    await readFile(join(home, "backups", backups[0], "SKILL.md"), "utf8"),
    "unknown local work",
  );
});

test("later sync distinguishes an unchanged base from a divergent local edit", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-three-way-"));
  const cleanTarget = join(root, "clean-agent");
  const editedTarget = join(root, "edited-agent");
  const cleanHome = join(root, "clean-state");
  const editedHome = join(root, "edited-state");

  await synchronize(
    desired([skill("base")]),
    [{ id: "codex", path: cleanTarget }],
    cleanHome,
  );
  const clean = await synchronize(
    { ...desired([skill("dashboard", "r2")]), generation: 2 },
    [{ id: "codex", path: cleanTarget }],
    cleanHome,
  );
  assert.equal(clean[0].status, "synchronized");
  assert.equal(
    await readFile(join(cleanTarget, "demo/SKILL.md"), "utf8"),
    "dashboard",
  );

  await synchronize(
    desired([skill("base")]),
    [{ id: "codex", path: editedTarget }],
    editedHome,
  );
  await writeFile(join(editedTarget, "demo/SKILL.md"), "local edit");
  const divergent = await synchronize(
    { ...desired([skill("dashboard", "r2")]), generation: 2 },
    [{ id: "codex", path: editedTarget }],
    editedHome,
  );
  assert.equal(divergent[0].status, "conflicted");
  assert.equal(
    divergent[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "local edit",
  );
  assert.equal(
    await readFile(join(editedTarget, "demo/SKILL.md"), "utf8"),
    "local edit",
  );
});

test("replace backs up conflicts and removal deletes only unchanged owned installs", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  await synchronize(
    {
      generation: 2,
      skills: [skill("two", "r2")],
      resolutions: { "s1:codex": "replace" },
    },
    agent,
    home,
  );
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agent,
    home,
  );
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
});

test("active lock prevents concurrent replay", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(home, { recursive: true })
      .then(() =>
        fs.writeFile(
          join(home, "sync.lock"),
          JSON.stringify({ pid: process.pid, createdAt: Date.now() }),
        ),
      ),
  );
  await assert.rejects(
    synchronize(
      desired([skill("one")]),
      [{ id: "codex", path: join(root, "agent") }],
      home,
    ),
    /already running/,
  );
});

test("stale interrupted lock is recovered", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(home, { recursive: true })
      .then(() =>
        fs.writeFile(
          join(home, "sync.lock"),
          JSON.stringify({ pid: 999999, createdAt: 1 }),
        ),
      ),
  );
  const receipts = await synchronize(
    desired([skill("one")]),
    [{ id: "codex", path: join(root, "agent") }],
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
});

test("invalid desired path fails without replacing last good files", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("good")]), agent, home);
  const bad = skill("bad", "r2");
  bad.files.push({ path: "../escape", content: "bad" });
  const receipts = await synchronize(
    { generation: 2, skills: [bad], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "failed");
  assert.match(receipts[0].message ?? "", /Unsafe skill path/);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "good");
});

test("unowned directories, extra files, removed files, and mode changes conflict with a full snapshot", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(join(target, "demo"), { recursive: true })
      .then(() =>
        fs.writeFile(
          join(target, "demo/local.bin"),
          Buffer.from([0xff, 0xfe, 2]),
        ),
      ),
  );
  let receipts = await synchronize(desired([skill("server")]), agent, home);
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].localFiles?.[0].encoding, "base64");
  receipts = await synchronize(
    {
      generation: 2,
      skills: [skill("server")],
      resolutions: { "s1:codex": "replace" },
    },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await writeFile(join(target, "demo/extra.txt"), "mine");
  await import("node:fs/promises").then(async (fs) => {
    await fs.rm(join(target, "demo/scripts/run.sh"));
    await fs.chmod(join(target, "demo/SKILL.md"), 0o600);
  });
  receipts = await synchronize(
    { generation: 3, skills: [skill("new", "r2")], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.deepEqual(receipts[0].localFiles?.map((f) => f.path).sort(), [
    "SKILL.md",
    "extra.txt",
  ]);
  assert.equal(
    receipts[0].localFiles?.find((f) => f.path === "SKILL.md")?.mode,
    0o600,
  );
});

test("install-time import preserves local directory and releases ownership before exclusion", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "mine");
  let receipts = await synchronize(
    {
      generation: 2,
      skills: [skill("new", "r2")],
      resolutions: { "s1:codex": "import" },
    },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "mine");
  assert.equal(
    receipts[0].localFiles?.find((f) => f.path === "SKILL.md")?.content,
    "mine",
  );
  receipts = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts.length, 0);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "mine");
});

test("one failed destination does not prevent another target from synchronizing", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const bad = skill("bad");
  bad.name = "../escape";
  const good = skill("good");
  good.id = "s2";
  good.name = "safe";
  const receipts = await synchronize(
    desired([bad, good]),
    [{ id: "codex", path: join(root, "agent") }],
    join(root, "state"),
  );
  assert.deepEqual(
    receipts.map((r) => r.status),
    ["failed", "synchronized"],
  );
  assert.equal(
    await readFile(join(root, "agent/safe/SKILL.md"), "utf8"),
    "good",
  );
});

test("journal recovery restores the last directory before retrying an interrupted replacement", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("original")]), agent, home);
  const destination = join(target, "demo");
  const oldPath = `${destination}.equip-old-test`;
  const stage = `${destination}.equip-stage-test`;
  await writeFile(join(destination, "SKILL.md"), "local-before-crash");
  const fs = await import("node:fs/promises");
  await fs.rename(destination, oldPath);
  await fs.mkdir(destination, { recursive: true });
  await fs.writeFile(join(destination, "SKILL.md"), "half-installed");
  await fs.writeFile(
    join(home, "transaction.json"),
    JSON.stringify({
      destination,
      oldPath,
      stage,
      hadOld: true,
      revision: "r2",
    }),
  );
  const receipts = await synchronize(
    { generation: 2, skills: [skill("new", "r2")], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(
    await readFile(join(destination, "SKILL.md"), "utf8"),
    "local-before-crash",
  );
});

test("interrupted updates require the exact committed transaction even for shared paths or unchanged revisions", async () => {
  for (const observed of [false, true]) {
    const root = await mkdtemp(join(tmpdir(), "equip-transaction-"));
    const target = join(root, "agent");
    const home = join(root, "state");
    const shared = join(root, "shared");
    const linked = skill("original");
    if (observed) {
      await synchronize(desired([linked]), [{ id: "codex", path: shared }], join(root, "seed"));
      await mkdir(target);
      await symlink(join(shared, "demo"), join(target, "demo"));
    }
    const targets = [{ id: "codex", path: target }, ...(observed ? [{ id: "claude-code", path: target }] : [])];
    await synchronize(desired([linked]), targets, home);
    const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
    const entries = Object.values(ledger.installs) as any[];
    const destination = entries[0].canonicalPath || entries[0].path;
    const incomingRevision = observed ? "r2" : "r1";
    if (observed) entries[1].revision = incomingRevision;
    await writeFile(join(home, "ledger.json"), JSON.stringify(ledger));
    await writeFile(join(destination, "SKILL.md"), "local-before-crash");
    const oldPath = `${destination}.equip-old-test`;
    await rename(destination, oldPath);
    await mkdir(destination);
    await writeFile(join(destination, "SKILL.md"), "half-installed");
    await writeFile(join(home, "transaction.json"), JSON.stringify({
      destination, oldPath, stage: `${destination}.equip-stage-test`, hadOld: true,
      revision: incomingRevision, transactionId: "not-yet-committed",
    }));
    const receipts = await synchronize(desired([linked]), targets, home);
    assert.ok(receipts.every(receipt => receipt.status === "conflicted"));
    assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "local-before-crash");
    if (observed) assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  }
});

test("explicit replace swaps a symlinked skill root without changing its target", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const external = join(root, "external");
  const fs = await import("node:fs/promises");
  await fs.mkdir(target);
  await fs.mkdir(external);
  await fs.writeFile(join(external, "private.txt"), "untouched");
  await fs.symlink(external, join(target, "demo"));
  const receipts = await synchronize(
    { ...desired([skill("server")]), resolutions: { "s1:codex": "replace" } },
    [{ id: "codex", path: target }],
    join(root, "state"),
  );
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(
    await readFile(join(external, "private.txt"), "utf8"),
    "untouched",
  );
  assert.equal((await fs.lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "server");
});

test("first-connect symlink resolutions preserve its external target", async () => {
  for (const action of ["import", "preserve"] as const) {
    const root = await mkdtemp(join(tmpdir(), `equip-linked-${action}-`));
    const target = join(root, "agent");
    const external = join(root, "external");
    const home = join(root, "state");
    await mkdir(target);
    await mkdir(join(external, "scripts"), { recursive: true });
    await writeFile(join(external, "SKILL.md"), "external local edit");
    await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", {
      mode: 0o755,
    });
    await symlink(external, join(target, "demo"));

    const receipts = await synchronize(
      {
        ...desired([skill("dashboard")]),
        resolutions: { "s1:codex::": action },
      },
      [{ id: "codex", path: target }],
      home,
    );

    assert.equal(receipts[0].status, "conflicted");
    assert.equal(receipts[0].managed, false);
    assert.equal(
      receipts[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
      "external local edit",
    );
    assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
    assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
  }
});

test("first-connect symlink replace backs up its pointer and contents without changing its target", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-linked-replace-"));
  const target = join(root, "agent");
  const external = join(root, "external");
  const home = join(root, "state");
  await mkdir(target);
  await mkdir(join(external, "scripts"), { recursive: true });
  await writeFile(join(external, "SKILL.md"), "external local edit");
  await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });
  await symlink(external, join(target, "demo"));

  const replaced = await synchronize(
    {
      ...desired([skill("dashboard")]),
      resolutions: { "s1:codex::": "replace" },
    },
    [{ id: "codex", path: target }],
    home,
  );

  assert.equal(replaced[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "dashboard");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
  const backups = await import("node:fs/promises").then((fs) =>
    fs.readdir(join(home, "backups")),
  );
  assert.equal(backups.length, 1);
  assert.equal(
    await readFile(join(home, "backups", backups[0], "contents/SKILL.md"), "utf8"),
    "external local edit",
  );
  assert.equal(
    JSON.parse(
      await readFile(join(home, "backups", backups[0], "original-link.json"), "utf8"),
    ).target,
    external,
  );

  const updated = await synchronize(
    { ...desired([skill("later", "r2")]), generation: 2 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(updated[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "later");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
});

test("replace reconciles a retargeted observed link and backs up its current pointer once", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-observed-retarget-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), original = join(root, "original"), external = join(root, "external"), home = join(root, "state");
  await mkdir(target);
  for (const [path, content] of [[original, "one"], [external, "external edit"]] as const) {
    await mkdir(join(path, "scripts"), { recursive: true });
    await writeFile(join(path, "SKILL.md"), content);
    await writeFile(join(path, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  }
  await symlink(original, join(target, "demo"));
  const agents = [{ id: "codex", path: target }];
  assert.equal((await synchronize(desired([skill("one")]), agents, home))[0].managed, false);
  await rm(join(target, "demo"));
  await symlink(external, join(target, "demo"));

  const replaced = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2, resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.notEqual(replaced[0].managed, false);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external edit");
  const backups = await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups")));
  assert.equal(backups.length, 2);
  const linkedBackup = backups.find(folder => folder.includes("-linked-"));
  assert.ok(linkedBackup);
  assert.equal(await readFile(join(home, "backups", linkedBackup, "contents/SKILL.md"), "utf8"), "external edit");
  assert.equal(JSON.parse(await readFile(join(home, "backups", linkedBackup, "original-link.json"), "utf8")).target, external);

  const repeated = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 3 },
    agents,
    home,
  );
  assert.equal(repeated[0].status, "synchronized");
  assert.equal(await (await import("node:fs/promises")).readdir(join(home, "backups")).then(items => items.length), 2);
});

test("replace reconciles a swapped managed link without changing its target", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-managed-retarget-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), external = join(root, "external"), home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agents, home);
  await mkdir(join(external, "scripts"), { recursive: true });
  await writeFile(join(external, "SKILL.md"), "swapped contents");
  await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  await rm(join(target, "demo"));
  await symlink(external, join(target, "demo"));

  const protectedResult = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2 },
    agents,
    home,
  );
  assert.equal(protectedResult[0].status, "conflicted");
  assert.equal(await readlink(join(target, "demo")), external);

  const replaced = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2, resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "swapped contents");
  const backups = await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups")));
  assert.equal(backups.length, 2);
  const linkedBackup = backups.find(folder => folder.includes("-linked-"));
  assert.ok(linkedBackup);
  assert.equal(await readFile(join(home, "backups", linkedBackup, "contents/SKILL.md"), "utf8"), "swapped contents");
  assert.equal(JSON.parse(await readFile(join(home, "backups", linkedBackup, "original-link.json"), "utf8")).target, external);
});

test("a canonical edit conflicts across profiles while resolutions stay isolated", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  const targets = [
    { id: "codex", profile: "work", path: join(root, "work") },
    { id: "codex", profile: "personal", path: join(root, "personal") },
  ];
  await synchronize(desired([skill("server")]), targets, home);
  await writeFile(join(root, "work/demo/SKILL.md"), "shared-local");
  const first = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex:work:": "import" } },
    targets,
    home,
  );
  assert.equal(
    first.find((r) => r.profile === "work")?.message,
    "Imported local files and released management",
  );
  assert.equal(
    first
      .find((r) => r.profile === "work")
      ?.localFiles?.find((f) => f.path === "SKILL.md")?.content,
    "shared-local",
  );
  assert.match(
    first.find((r) => r.profile === "personal")?.message ?? "",
    /not removed/,
  );
  const second = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    targets,
    home,
  );
  assert.equal(
    second.some((r) => r.profile === "work"),
    false,
  );
  assert.equal(second.filter((r) => r.profile === "personal").length, 1);
  assert.equal(
    await readFile(join(root, "work/demo/SKILL.md"), "utf8"),
    "shared-local",
  );
});

test("removal import preserves non-UTF8 bytes without NUL as base64", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  const bytes = Buffer.from([0xff, 0xfe, 0xfd]);
  await writeFile(join(target, "demo/local.bin"), bytes);
  const receipts = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "import" } },
    agents,
    home,
  );
  const file = receipts[0].localFiles?.find(
    (item) => item.path === "local.bin",
  );
  assert.equal(file?.encoding, "base64");
  assert.deepEqual(Buffer.from(file!.content, "base64"), bytes);
  assert.equal(
    await readFile(join(target, "demo/local.bin")).then((data) =>
      data.equals(bytes),
    ),
    true,
  );
});

test("removal replace backs up changed directory and removes it", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "local");
  const receipts = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  const backups = await import("node:fs/promises").then((fs) =>
    fs.readdir(join(home, "backups")),
  );
  assert.equal(
    await readFile(join(home, "backups", backups[0], "local.txt"), "utf8"),
    "local",
  );
});

test("target rules are per-device overrides while unspecified agents stay enabled", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const configured = skill("one");
  configured.targets = [
    { deviceId: "device-a", agent: "codex", enabled: false },
  ];
  const receipts = await synchronize(
    desired([configured]),
    [
      { id: "codex", path: join(root, "codex"), deviceId: "device-a" },
      { id: "claude-code", path: join(root, "claude"), deviceId: "device-a" },
    ],
    join(root, "state"),
  );
  assert.deepEqual(
    receipts.map((r) => r.agent),
    ["claude-code"],
  );
  await assert.rejects(readFile(join(root, "codex/demo/SKILL.md")));
  assert.equal(
    await readFile(join(root, "claude/demo/SKILL.md"), "utf8"),
    "one",
  );
});

test("a clean managed skill rename moves ownership to the new folder", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    { generation: 2, skills: [renamed], resolutions: {} },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  assert.equal(await readFile(join(target, "renamed/SKILL.md"), "utf8"), "new");
});

test("a managed skill rename preserves a locally modified old folder", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    { generation: 2, skills: [renamed], resolutions: {} },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].path, join(target, "demo"));
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
  await assert.rejects(readFile(join(target, "renamed/SKILL.md")));
});

test("rename import releases modified old ownership before exclusion", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const first = await synchronize(
    {
      generation: 2,
      skills: [renamed],
      resolutions: { "s1:codex::": "import" },
    },
    agents,
    home,
  );
  assert.equal(first[0].status, "conflicted");
  assert.equal(
    first[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "local",
  );
  const second = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agents,
    home,
  );
  assert.equal(second.length, 0);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
});

test("rename replace backs up modified old and occupied new folders", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "old-local");
  const fs = await import("node:fs/promises");
  await fs.mkdir(join(target, "renamed"));
  await writeFile(join(target, "renamed/local.txt"), "new-local");
  const renamed = skill("server", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    {
      generation: 2,
      skills: [renamed],
      resolutions: { "s1:codex::": "replace" },
    },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  assert.equal(
    await readFile(join(target, "renamed/SKILL.md"), "utf8"),
    "server",
  );
  const backups = await fs.readdir(join(home, "backups"));
  const contents = await Promise.all(
    backups.map(async (folder) =>
      readFile(join(home, "backups", folder, "local.txt"), "utf8").catch(
        () => "",
      ),
    ),
  );
  assert.deepEqual(contents.sort(), ["new-local", "old-local"]);
});

test("an unchanged revision leaves the installed directory in place", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  const value = skill("same");
  await synchronize(desired([value]), agents, home);
  const before = await stat(join(target, "demo"));
  await synchronize(
    { generation: 2, skills: [value], resolutions: {} },
    agents,
    home,
  );
  const after = await stat(join(target, "demo"));
  assert.equal(after.ino, before.ino);
  assert.equal(after.mtimeMs, before.mtimeMs);
});

test("shared agent directories remain managed, survive one exclusion, and remove their store after all exclusions", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "equip-shared-ownership-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), path = join(root, "shared");
  const agents = [{ id: "one", path }, { id: "two", path }];
  const value = skill("shared");
  const installed = await synchronize(desired([value]), agents, home);
  assert.ok(installed.every(receipt => receipt.status === "synchronized" && receipt.managed !== false));
  const excluded = { ...value, targets: [{ deviceId: "", agent: "one", enabled: false }] };
  const partial = await synchronize({ ...desired([excluded]), generation: 2 }, agents, home);
  assert.ok(partial.every(receipt => receipt.status === "synchronized"));
  assert.equal(await readFile(join(path, "demo/SKILL.md"), "utf8"), "shared");
  await synchronize({ generation: 3, skills: [], resolutions: {} }, agents, home);
  assert.equal(await lstat(join(path, "demo")).catch(() => null), null);
  assert.equal(await lstat(join(home, "skills/demo")).catch(() => null), null);
});


test("removal preserves a locally substituted symlink even when its contents match", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-removal-link-"));
  const target = join(root, "agent"), home = join(root, "state");
  const targets = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), targets, home);
  await rename(join(target, "demo"), join(root, "local-work"));
  await rm(join(root, "local-work"));
  await symlink(join(home, "skills/demo"), join(root, "local-work"));
  await symlink(join(root, "local-work"), join(target, "demo"));
  const receipts = await synchronize(desired([]), targets, home);
  assert.equal(receipts[0].status, "conflicted");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(root, "local-work/SKILL.md"), "utf8"), "one");
});

test("releasing an observed link protects its preexisting canonical source from other managed removals", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-observed-canonical-"));
  const home = join(root, "state"), original = join(root, "original"), peer = join(root, "peer");
  await synchronize(desired([skill("one")]), [{ id: "codex", path: join(root, "seed-target") }], join(root, "seed"));
  await cp(join(root, "seed/skills/demo"), join(home, "skills/demo"), { recursive: true });
  await mkdir(original);
  await symlink(join(home, "skills/demo"), join(original, "demo"));
  const linked = skill("one");
  const targets = [{ id: "codex", path: original }, { id: "claude-code", path: peer }];
  assert.ok((await synchronize(desired([linked]), targets, home)).every(r => r.status === "synchronized"));
  await synchronize(desired([]), targets, home);
  assert.equal((await lstat(join(original, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(original, "demo/SKILL.md"), "utf8"), "one");
  await assert.rejects(lstat(join(peer, "demo")), /ENOENT/);
});

test("a stale failed destination cannot block the next canonical update when another baseline confirms it", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-partial-baseline-"));
  const home = join(root, "state"), targets = [{ id: "codex", path: join(root, "one") }, { id: "claude-code", path: join(root, "two") }];
  await synchronize(desired([skill("one")]), targets, home);
  await rm(join(targets[1].path, "demo"));
  await symlink(join(root, "user-link"), join(targets[1].path, "demo"));
  const second = await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, targets, home);
  assert.deepEqual(second.map(r => r.status), ["synchronized", "conflicted"]);
  const third = await synchronize({ ...desired([skill("three", "r3")]), generation: 3 }, targets, home);
  assert.deepEqual(third.map(r => r.status), ["synchronized", "conflicted"]);
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "three");
});


test("shared agent roots adopt an updated Equip link without changing the original repository", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-central-observed-"));
  const home = join(root, "state"), repository = join(root, "repository"), target = join(root, "agent"), alias = join(root, "alias");
  try {
    await mkdir(join(repository, "demo/scripts"), { recursive: true });
    await writeFile(join(repository, "demo/SKILL.md"), "one");
    await writeFile(join(repository, "demo/scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
    await mkdir(target);
    await symlink(join(repository, "demo"), join(target, "demo"));
    await symlink(target, alias);
    const targets = [{ id: "codex", path: target }, { id: "claude-code", path: alias }];
    assert.ok((await synchronize(desired([skill("one")]), targets, home)).every(r => r.status === "synchronized"));
    const updated = await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, targets, home);
    assert.ok(updated.every(r => r.status === "synchronized"));
    assert.ok(updated.every(r => r.managed !== false));
    assert.equal(await readFile(join(repository, "demo/SKILL.md"), "utf8"), "one");
    assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
    assert.equal(await readFile(join(alias, "demo/SKILL.md"), "utf8"), "two");
    assert.ok((await synchronize({ ...desired([]), generation: 3 }, targets, home)).every(r => r.status === "synchronized"));
    await assert.rejects(lstat(join(target, "demo")), /ENOENT/);
    assert.equal(await readFile(join(repository, "demo/SKILL.md"), "utf8"), "one");
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("links resolve correctly through agent roots at different physical depths", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-alias-"));
  const physical = join(root, "nested/configuration/skills"), alias = join(root, "agent"), home = join(root, "state");
  try {
    await mkdir(physical, { recursive: true });
    await symlink(physical, alias);
    const target = [{ id: "codex", path: alias }];
    assert.equal((await synchronize(desired([skill("one")]), target, home))[0].status, "synchronized");
    assert.equal(await readFile(join(alias, "demo/SKILL.md"), "utf8"), "one");
    assert.equal((await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, target, home))[0].status, "synchronized");
    assert.equal(await readFile(join(physical, "demo/SKILL.md"), "utf8"), "two");
    assert.equal((await synchronize({ ...desired([]), generation: 3 }, target, home))[0].status, "synchronized");
    await assert.rejects(lstat(join(physical, "demo")), /ENOENT/);
  } finally { await rm(root, { recursive: true, force: true }); }
});
