import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import fsPromises, { mkdtemp, readFile, readdir, stat, writeFile, mkdir, symlink, lstat, rename, rm, cp, chmod, readlink, realpath } from "node:fs/promises";
import { syncBuiltinESMExports } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import test from "node:test";
import type { DesiredState, Skill } from "../shared/types.ts";
import { synchronize as synchronizeRaw } from "../cli/sync.ts";
import { sameFileHashes, sameInstalledFileHashes } from "../cli/file-state.ts";

const synchronize = (
  desired: DesiredState,
  targets: Parameters<typeof synchronizeRaw>[1],
  home: string,
) => synchronizeRaw(desired, targets, home, async () => {});

function skill(content: string, revision = "r1"): Skill {
  return {
    id: "s1",
    name: "demo",
    title: "Demo",
    description: "",
    author: "test",
    source: "test",
    kind: "custom",
    category: "Test",
    icon: "",
    color: "",
    selected: true,
    enabled: true,
    autoUpdate: true,
    revision,
    versions: [],
    files: [
      { path: "SKILL.md", content },
      { path: "scripts/run.sh", content: "#!/bin/sh\n", mode: 0o755 },
    ],
    requirements: [],
    targets: [],
    updatedAt: new Date().toISOString(),
  };
}
const desired = (s: Skill[]): DesiredState => ({
  generation: 1,
  skills: s,
  resolutions: {},
});

test("running Python skill scripts does not conflict on generated bytecode", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-python-cache-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), target = join(root, "agent");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agents, home);
  const cache = join(target, "demo/scripts/__pycache__");
  await mkdir(cache, { recursive: true });
  await writeFile(join(cache, "search.cpython-313.pyc"), Buffer.from([0, 255, 3]));
  const receipts = await synchronize(desired([skill("one")]), agents, home);
  assert.equal(receipts[0].status, "synchronized");
  assert.deepEqual(await readFile(join(cache, "search.cpython-313.pyc")), Buffer.from([0, 255, 3]));
  await writeFile(join(target, "demo/SKILL.md"), "edited instructions");
  const modified = await synchronize(desired([skill("one")]), agents, home);
  assert.equal(modified[0].status, "conflicted");
  assert.ok(modified[0].localFiles?.some(file => file.path.endsWith(".pyc")), "Full recovery snapshots still include the cache");
});

test("bundled bytecode and unexpected symlinks remain part of conflict detection", () => {
  const path = "scripts/__pycache__/search.cpython-313.pyc";
  const hash = `420:${"a".repeat(64)}`;
  assert.ok(sameInstalledFileHashes({ [path]: hash }, {}));
  assert.ok(!sameInstalledFileHashes({}, { [path]: hash }), "Deleting a bundled file still matters");
  assert.ok(!sameInstalledFileHashes({ [path]: `420:${"b".repeat(64)}` }, { [path]: hash }));
  assert.ok(!sameInstalledFileHashes({ [path]: `symlink:${"a".repeat(64)}` }, {}));
  assert.ok(!sameInstalledFileHashes({ "scripts/__pycache__/notes.md": hash }, {}));
});

test("same-content preexisting skill links become canonical without altering or backing up the source", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-portable-link-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const source = join(root, "original/demo"), target = join(root, "claude"), home = join(root, "state");
  await mkdir(join(source, "scripts"), { recursive: true });
  await mkdir(target);
  await writeFile(join(source, "SKILL.md"), "one");
  await writeFile(join(source, "scripts/run.sh"), "#!/bin/sh\n");
  await chmod(join(source, "SKILL.md"), 0o664);
  await chmod(join(source, "scripts/run.sh"), 0o775);
  await symlink(source, join(target, "demo"));
  const agent = [{ id: "claude-code", path: target }];
  const receipts = await synchronize(desired([skill("one")]), agent, home);
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(receipts[0].revision, "r1");
  assert.notEqual(receipts[0].managed, false);
  assert.equal(await realpath(join(target, "demo")), await realpath(join(home, "skills/demo")));
  assert.equal((await stat(join(source, "SKILL.md"))).mode & 0o777, 0o664);
  assert.equal((await stat(join(source, "scripts/run.sh"))).mode & 0o777, 0o775);
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
  await chmod(join(source, "SKILL.md"), 0o600);
  assert.equal((await synchronize(desired([skill("two", "r2")]), agent, home))[0].status, "synchronized");
  assert.equal(await readFile(join(source, "SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
});

test("legacy observed exact matches migrate to the canonical link without a source backup", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-observed-migration-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const source = join(root, "repository/demo"), target = join(root, "agent"), home = join(root, "state");
  await mkdir(join(source, "scripts"), { recursive: true });
  await mkdir(target);
  await writeFile(join(source, "SKILL.md"), "one");
  await writeFile(join(source, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  await symlink(source, join(target, "demo"));
  await synchronize(desired([skill("one")]), [{ id: "codex", path: target }], home);

  const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
  const entry = Object.values(ledger.installs)[0] as any;
  entry.observed = true;
  entry.canonicalPath = await realpath(source);
  await writeFile(join(home, "ledger.json"), JSON.stringify(ledger));
  await rm(join(target, "demo"));
  await symlink(source, join(target, "demo"));

  const receipts = await synchronize(desired([skill("one")]), [{ id: "codex", path: target }], home);
  assert.equal(receipts[0].status, "synchronized");
  assert.notEqual(receipts[0].managed, false);
  assert.equal(await realpath(join(target, "demo")), await realpath(join(home, "skills/demo")));
  assert.equal(await readFile(join(source, "SKILL.md"), "utf8"), "one");
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
});

test("managed skill permission changes do not block sync, update, or removal; executable edits do", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-portable-managed-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await chmod(join(target, "demo/SKILL.md"), 0o600);
  await chmod(join(target, "demo/scripts/run.sh"), 0o700);
  assert.equal((await synchronize(desired([skill("one")]), agent, home))[0].status, "synchronized");
  assert.equal((await synchronize(desired([skill("two", "r2")]), agent, home))[0].status, "synchronized");
  await chmod(join(target, "demo/scripts/run.sh"), 0o644);
  const conflicted = await synchronize(desired([skill("three", "r3")]), agent, home);
  assert.equal(conflicted[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  await chmod(join(target, "demo/scripts/run.sh"), 0o775);
  assert.equal((await synchronize(desired([]), agent, home))[0].status, "synchronized");
  assert.equal(await lstat(join(target, "demo")).catch(() => null), null);
});

test("legacy hash comparison preserves file kind and content and accounts for Windows permissions", () => {
  const digest = createHash("sha256").update("same").digest("hex");
  assert.ok(sameFileHashes({ file: `432:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(!sameFileHashes({ file: `493:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(sameFileHashes({ file: `438:${digest}` }, { file: `493:${digest}` }, "win32"));
  assert.ok(!sameFileHashes({ file: `symlink:${digest}` }, { file: `420:${digest}` }, "linux"));
  assert.ok(!sameFileHashes({ file: `420:${digest}` }, {}, "linux"));
});

test("Equip immediately adopts matching linked installations and preserves their original sources", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-nova-links-"));
  const target = join(root, "agent"), shared = join(root, "shared"), home = join(root, "state");
  await synchronize(desired([skill("one")]), [{ id: "codex", path: shared }], join(root, "seed"));
  await mkdir(target);
  await symlink(join(shared, "demo"), join(target, "demo"));
  const linked = skill("one");
  const receipts = await synchronize(desired([linked]), [{ id: "codex", path: target }], home);
  assert.equal(receipts[0].status, "synchronized");
  assert.notEqual(receipts[0].managed, false);
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await realpath(join(target, "demo")), await realpath(join(home, "skills/demo")));
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);

  const updated = skill("two", "r2");
  const updateReceipts = await synchronize(
    { ...desired([updated]), generation: 2 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(updateReceipts[0].status, "synchronized");
  assert.notEqual(updateReceipts[0].managed, false);
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  await writeFile(join(target, "demo/SKILL.md"), "local work");
  const changed = skill("three", "r3");
  const conflict = await synchronize(
    { ...desired([changed]), generation: 3 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(conflict[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local work");
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");

  const removed = await synchronize(
    { generation: 4, skills: [], resolutions: {} },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(removed[0].status, "conflicted");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local work");
  assert.equal(await readFile(join(shared, "demo/SKILL.md"), "utf8"), "one");
});

test("identical revision synchronizes to two isolated devices", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  const a = join(root, "a");
  const b = join(root, "b");
  const receipts = await synchronize(
    desired([skill("one")]),
    [
      { id: "codex", path: a },
      { id: "claude-code", path: b },
    ],
    home,
  );
  assert.deepEqual(
    receipts.map((r) => r.status),
    ["synchronized", "synchronized"],
  );
  assert.equal(await readFile(join(a, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(b, "demo/SKILL.md"), "utf8"), "one");
  assert.equal((await lstat(join(a, "demo"))).isSymbolicLink(), true);
  assert.equal((await lstat(join(b, "demo"))).isSymbolicLink(), true);
  const fs = await import("node:fs/promises");
  assert.equal(
    await fs.realpath(join(a, "demo")),
    await fs.realpath(join(home, "skills/demo")),
  );
  assert.equal(
    await fs.realpath(join(b, "demo")),
    await fs.realpath(join(home, "skills/demo")),
  );
});

test("a clean legacy managed directory migrates to the canonical link", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-migrate-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(target, "demo/scripts"), { recursive: true });
  await writeFile(join(target, "demo/SKILL.md"), "one");
  await writeFile(join(target, "demo/scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  const hashes = {
    "SKILL.md": `${0o644}:${createHash("sha256").update("one").digest("hex")}`,
    "scripts/run.sh": `${0o755}:${createHash("sha256").update("#!/bin/sh\n").digest("hex")}`,
  };
  await mkdir(home);
  await writeFile(join(home, "ledger.json"), JSON.stringify({ generation: 1, installs: {
    "s1:codex::": { skillId: "s1", agent: "codex", revision: "r1", files: hashes, path: join(target, "demo") },
  } }));
  const receipts = await synchronize(desired([skill("one")]), [{ id: "codex", path: target }], home);
  assert.equal(receipts[0].status, "synchronized");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "one");
});

test("local edits conflict and preserve the last good install", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const receipts = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2 },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
});

test("first connect preserves a same-name local skill when no baseline is known", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-unknown-base-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(target, "demo/scripts"), { recursive: true });
  await writeFile(join(target, "demo/SKILL.md"), "edited before Equip");
  await writeFile(join(target, "demo/scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });

  const receipts = await synchronize(
    desired([skill("dashboard")]),
    [{ id: "codex", path: target }],
    home,
  );

  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].revision, "");
  assert.equal(
    receipts[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "edited before Equip",
  );
  assert.equal(
    await readFile(join(target, "demo/SKILL.md"), "utf8"),
    "edited before Equip",
  );
  assert.equal(
    await readFile(join(home, "skills/demo/SKILL.md"), "utf8"),
    "dashboard",
  );
});

test("replacing an unknown-base canonical conflict keeps a recovery copy", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-canonical-recovery-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  await mkdir(join(home, "skills/demo/scripts"), { recursive: true });
  await writeFile(join(home, "skills/demo/SKILL.md"), "unknown local work");
  await writeFile(join(home, "skills/demo/scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });

  const conflict = await synchronize(
    desired([skill("dashboard")]),
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(conflict[0].status, "conflicted");
  assert.equal(
    await readFile(join(home, "skills/demo/SKILL.md"), "utf8"),
    "unknown local work",
  );

  const replaced = await synchronize(
    {
      ...desired([skill("dashboard")]),
      generation: 2,
      resolutions: { "s1:codex::": "replace" },
    },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.equal(
    await readFile(join(target, "demo/SKILL.md"), "utf8"),
    "dashboard",
  );
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
});

test("later sync distinguishes an unchanged base from a divergent local edit", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-three-way-"));
  const cleanTarget = join(root, "clean-agent");
  const editedTarget = join(root, "edited-agent");
  const cleanHome = join(root, "clean-state");
  const editedHome = join(root, "edited-state");

  await synchronize(
    desired([skill("base")]),
    [{ id: "codex", path: cleanTarget }],
    cleanHome,
  );
  const clean = await synchronize(
    { ...desired([skill("dashboard", "r2")]), generation: 2 },
    [{ id: "codex", path: cleanTarget }],
    cleanHome,
  );
  assert.equal(clean[0].status, "synchronized");
  assert.equal(
    await readFile(join(cleanTarget, "demo/SKILL.md"), "utf8"),
    "dashboard",
  );

  await synchronize(
    desired([skill("base")]),
    [{ id: "codex", path: editedTarget }],
    editedHome,
  );
  await writeFile(join(editedTarget, "demo/SKILL.md"), "local edit");
  const divergent = await synchronize(
    { ...desired([skill("dashboard", "r2")]), generation: 2 },
    [{ id: "codex", path: editedTarget }],
    editedHome,
  );
  assert.equal(divergent[0].status, "conflicted");
  assert.equal(
    divergent[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "local edit",
  );
  assert.equal(
    await readFile(join(editedTarget, "demo/SKILL.md"), "utf8"),
    "local edit",
  );
});

test("replace archives conflicts and removal deletes only unchanged owned installs", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  await synchronize(
    {
      generation: 2,
      skills: [skill("two", "r2")],
      resolutions: { "s1:codex": "replace" },
    },
    agent,
    home,
  );
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agent,
    home,
  );
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
});

test("active lock prevents concurrent replay", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(home, { recursive: true })
      .then(() =>
        fs.writeFile(
          join(home, "sync.lock"),
          JSON.stringify({ pid: process.pid, createdAt: Date.now() }),
        ),
      ),
  );
  await assert.rejects(
    synchronize(
      desired([skill("one")]),
      [{ id: "codex", path: join(root, "agent") }],
      home,
    ),
    /already running/,
  );
});

test("stale interrupted lock is recovered", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(home, { recursive: true })
      .then(() =>
        fs.writeFile(
          join(home, "sync.lock"),
          JSON.stringify({ pid: 999999, createdAt: 1 }),
        ),
      ),
  );
  const receipts = await synchronize(
    desired([skill("one")]),
    [{ id: "codex", path: join(root, "agent") }],
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
});

test("invalid desired path fails without replacing last good files", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("good")]), agent, home);
  const bad = skill("bad", "r2");
  bad.files.push({ path: "../escape", content: "bad" });
  const receipts = await synchronize(
    { generation: 2, skills: [bad], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "failed");
  assert.match(receipts[0].message ?? "", /Unsafe skill path/);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "good");
});

test("unowned directories, extra files, removed files, and mode changes conflict with a full snapshot", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await import("node:fs/promises").then((fs) =>
    fs
      .mkdir(join(target, "demo"), { recursive: true })
      .then(() =>
        fs.writeFile(
          join(target, "demo/local.bin"),
          Buffer.from([0xff, 0xfe, 2]),
        ),
      ),
  );
  let receipts = await synchronize(desired([skill("server")]), agent, home);
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].localFiles?.[0].encoding, "base64");
  receipts = await synchronize(
    {
      generation: 2,
      skills: [skill("server")],
      resolutions: { "s1:codex": "replace" },
    },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await writeFile(join(target, "demo/extra.txt"), "mine");
  await import("node:fs/promises").then(async (fs) => {
    await fs.rm(join(target, "demo/scripts/run.sh"));
    await fs.chmod(join(target, "demo/SKILL.md"), 0o600);
  });
  receipts = await synchronize(
    { generation: 3, skills: [skill("new", "r2")], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.deepEqual(receipts[0].localFiles?.map((f) => f.path).sort(), [
    "SKILL.md",
    "extra.txt",
  ]);
  assert.equal(
    receipts[0].localFiles?.find((f) => f.path === "SKILL.md")?.mode,
    0o600,
  );
});

test("install-time import preserves local directory and releases ownership before exclusion", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agent, home);
  await writeFile(join(target, "demo/SKILL.md"), "mine");
  let receipts = await synchronize(
    {
      generation: 2,
      skills: [skill("new", "r2")],
      resolutions: { "s1:codex": "import" },
    },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "mine");
  assert.equal(
    receipts[0].localFiles?.find((f) => f.path === "SKILL.md")?.content,
    "mine",
  );
  receipts = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts.length, 0);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "mine");
});

test("one failed destination does not prevent another target from synchronizing", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const bad = skill("bad");
  bad.name = "../escape";
  const good = skill("good");
  good.id = "s2";
  good.name = "safe";
  const receipts = await synchronize(
    desired([bad, good]),
    [{ id: "codex", path: join(root, "agent") }],
    join(root, "state"),
  );
  assert.deepEqual(
    receipts.map((r) => r.status),
    ["failed", "synchronized"],
  );
  assert.equal(
    await readFile(join(root, "agent/safe/SKILL.md"), "utf8"),
    "good",
  );
});

test("journal recovery restores the last directory before retrying an interrupted replacement", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agent = [{ id: "codex", path: target }];
  await synchronize(desired([skill("original")]), agent, home);
  const destination = join(target, "demo");
  const oldPath = `${destination}.equip-old-test`;
  const stage = `${destination}.equip-stage-test`;
  await writeFile(join(destination, "SKILL.md"), "local-before-crash");
  const fs = await import("node:fs/promises");
  await fs.rename(destination, oldPath);
  await fs.mkdir(destination, { recursive: true });
  await fs.writeFile(join(destination, "SKILL.md"), "half-installed");
  await fs.writeFile(
    join(home, "transaction.json"),
    JSON.stringify({
      destination,
      oldPath,
      stage,
      hadOld: true,
      revision: "r2",
      skillId: "s1",
      expectedFiles: { "SKILL.md": `420:${createHash("sha256").update("half-installed").digest("hex")}` },
    }),
  );
  const receipts = await synchronize(
    { generation: 2, skills: [skill("new", "r2")], resolutions: {} },
    agent,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(
    await readFile(join(destination, "SKILL.md"), "utf8"),
    "local-before-crash",
  );
});

test("journal recovery archives unexpected destination edits before rollback", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-recovery-edit-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("original")]), agents, home);
  const destination = join(target, "demo"), oldPath = `${destination}.equip-old-test`;
  await rename(destination, oldPath);
  await mkdir(destination);
  await writeFile(join(destination, "SKILL.md"), "unexpected local edit");
  await writeFile(join(home, "transaction.json"), JSON.stringify({
    destination, oldPath, stage: `${destination}.equip-stage-test`, hadOld: true,
    revision: "r2", transactionId: "interrupted", skillId: "s1",
    expectedFiles: { "SKILL.md": `420:${createHash("sha256").update("staged").digest("hex")}` },
  }));
  const archived: Array<{files:Array<{path:string;content:string}>}> = [];
  const receipts = await synchronizeRaw(desired([skill("original")]), agents, home,
    async payload => { archived.push(payload as typeof archived[number]); });
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(archived[0].files.find(file => file.path === "SKILL.md")?.content, "unexpected local edit");
  assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "original");

  await rename(destination, oldPath);
  await mkdir(destination);
  await writeFile(join(destination, "SKILL.md"), "preserve without archive");
  await writeFile(join(home, "transaction.json"), JSON.stringify({
    destination, oldPath, stage: `${destination}.equip-stage-test`, hadOld: true,
    revision: "r3", transactionId: "interrupted-again", skillId: "s1",
    expectedFiles: { "SKILL.md": `420:${createHash("sha256").update("staged again").digest("hex")}` },
  }));
  await assert.rejects(synchronizeRaw(desired([skill("original")]), agents, home), /require recovery archiving/);
  assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "preserve without archive");
});

test("legacy journal recovery preserves an unverifiable destination", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-legacy-recovery-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("original")]), agents, home);
  const destination = join(target, "demo"), oldPath = `${destination}.equip-old-test`;
  await rename(destination, oldPath);
  await mkdir(destination);
  await writeFile(join(destination, "SKILL.md"), "unverifiable");
  await writeFile(join(home, "transaction.json"), JSON.stringify({
    destination, oldPath, stage: `${destination}.equip-stage-test`, hadOld: true, revision: "r2",
  }));
  await assert.rejects(
    synchronizeRaw(desired([skill("original")]), agents, home, async () => {}),
    /legacy skill update requires manual recovery/,
  );
  assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "unverifiable");
  assert.ok(await lstat(join(home, "transaction.json")));
});

test("interrupted updates require the exact committed transaction even for shared paths or unchanged revisions", async () => {
  for (const observed of [false, true]) {
    const root = await mkdtemp(join(tmpdir(), "equip-transaction-"));
    const target = join(root, "agent");
    const home = join(root, "state");
    const shared = join(root, "shared");
    const linked = skill("original");
    if (observed) {
      await synchronize(desired([linked]), [{ id: "codex", path: shared }], join(root, "seed"));
      await mkdir(target);
      await symlink(join(shared, "demo"), join(target, "demo"));
    }
    const targets = [{ id: "codex", path: target }, ...(observed ? [{ id: "claude-code", path: target }] : [])];
    await synchronize(desired([linked]), targets, home);
    const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
    const entries = Object.values(ledger.installs) as any[];
    const destination = entries[0].canonicalPath || entries[0].path;
    const incomingRevision = observed ? "r2" : "r1";
    if (observed) entries[1].revision = incomingRevision;
    await writeFile(join(home, "ledger.json"), JSON.stringify(ledger));
    await writeFile(join(destination, "SKILL.md"), "local-before-crash");
    const oldPath = `${destination}.equip-old-test`;
    await rename(destination, oldPath);
    await mkdir(destination);
    await writeFile(join(destination, "SKILL.md"), "half-installed");
    await writeFile(join(home, "transaction.json"), JSON.stringify({
      destination, oldPath, stage: `${destination}.equip-stage-test`, hadOld: true,
      revision: incomingRevision, transactionId: "not-yet-committed",
      skillId: "s1",
      expectedFiles: { "SKILL.md": `420:${createHash("sha256").update("half-installed").digest("hex")}` },
    }));
    const receipts = await synchronize(desired([linked]), targets, home);
    assert.ok(receipts.every(receipt => receipt.status === "conflicted"));
    assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "local-before-crash");
    if (observed) assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  }
});

test("explicit replace swaps a symlinked skill root without changing its target", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const external = join(root, "external");
  const fs = await import("node:fs/promises");
  await fs.mkdir(target);
  await fs.mkdir(external);
  await fs.writeFile(join(external, "private.txt"), "untouched");
  await fs.symlink(external, join(target, "demo"));
  const receipts = await synchronize(
    { ...desired([skill("server")]), resolutions: { "s1:codex": "replace" } },
    [{ id: "codex", path: target }],
    join(root, "state"),
  );
  assert.equal(receipts[0].status, "synchronized");
  assert.equal(
    await readFile(join(external, "private.txt"), "utf8"),
    "untouched",
  );
  assert.equal((await fs.lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "server");
});

test("first-connect symlink resolutions preserve its external target", async () => {
  for (const action of ["import", "preserve"] as const) {
    const root = await mkdtemp(join(tmpdir(), `equip-linked-${action}-`));
    const target = join(root, "agent");
    const external = join(root, "external");
    const home = join(root, "state");
    await mkdir(target);
    await mkdir(join(external, "scripts"), { recursive: true });
    await writeFile(join(external, "SKILL.md"), "external local edit");
    await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", {
      mode: 0o755,
    });
    await symlink(external, join(target, "demo"));

    const receipts = await synchronize(
      {
        ...desired([skill("dashboard")]),
        resolutions: { "s1:codex::": action },
      },
      [{ id: "codex", path: target }],
      home,
    );

    assert.equal(receipts[0].status, "conflicted");
    assert.equal(receipts[0].managed, false);
    assert.equal(
      receipts[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
      "external local edit",
    );
    assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
    assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
  }
});

test("first-connect symlink replace archives its contents without changing its target", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-linked-replace-"));
  const target = join(root, "agent");
  const external = join(root, "external");
  const home = join(root, "state");
  await mkdir(target);
  await mkdir(join(external, "scripts"), { recursive: true });
  await writeFile(join(external, "SKILL.md"), "external local edit");
  await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", {
    mode: 0o755,
  });
  await symlink(external, join(target, "demo"));

  const replaced = await synchronize(
    {
      ...desired([skill("dashboard")]),
      resolutions: { "s1:codex::": "replace" },
    },
    [{ id: "codex", path: target }],
    home,
  );

  assert.equal(replaced[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "dashboard");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);

  const updated = await synchronize(
    { ...desired([skill("later", "r2")]), generation: 2 },
    [{ id: "codex", path: target }],
    home,
  );
  assert.equal(updated[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "later");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external local edit");
});

test("replace reconciles a retargeted managed link and archives its current contents once", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-observed-retarget-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), original = join(root, "original"), external = join(root, "external"), home = join(root, "state");
  await mkdir(target);
  for (const [path, content] of [[original, "one"], [external, "external edit"]] as const) {
    await mkdir(join(path, "scripts"), { recursive: true });
    await writeFile(join(path, "SKILL.md"), content);
    await writeFile(join(path, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  }
  await symlink(original, join(target, "demo"));
  const agents = [{ id: "codex", path: target }];
  assert.notEqual((await synchronize(desired([skill("one")]), agents, home))[0].managed, false);
  await rm(join(target, "demo"));
  await symlink(external, join(target, "demo"));

  const replaced = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2, resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.notEqual(replaced[0].managed, false);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "external edit");
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);

  const repeated = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 3 },
    agents,
    home,
  );
  assert.equal(repeated[0].status, "synchronized");
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
});

test("replace reconciles a swapped managed link without changing its target", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-managed-retarget-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), external = join(root, "external"), home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), agents, home);
  await mkdir(join(external, "scripts"), { recursive: true });
  await writeFile(join(external, "SKILL.md"), "swapped contents");
  await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  await rm(join(target, "demo"));
  await symlink(external, join(target, "demo"));

  const protectedResult = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2 },
    agents,
    home,
  );
  assert.equal(protectedResult[0].status, "conflicted");
  assert.equal(await readlink(join(target, "demo")), external);

  const replaced = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2, resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(replaced[0].status, "synchronized");
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "two");
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "swapped contents");
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
});

test("a canonical edit conflicts across profiles while resolutions stay isolated", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const home = join(root, "state");
  const targets = [
    { id: "codex", profile: "work", path: join(root, "work") },
    { id: "codex", profile: "personal", path: join(root, "personal") },
  ];
  await synchronize(desired([skill("server")]), targets, home);
  await writeFile(join(root, "work/demo/SKILL.md"), "shared-local");
  const first = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex:work:": "import" } },
    targets,
    home,
  );
  assert.equal(
    first.find((r) => r.profile === "work")?.message,
    "Imported local files and released management",
  );
  assert.equal(
    first
      .find((r) => r.profile === "work")
      ?.localFiles?.find((f) => f.path === "SKILL.md")?.content,
    "shared-local",
  );
  assert.match(
    first.find((r) => r.profile === "personal")?.message ?? "",
    /not removed/,
  );
  const second = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    targets,
    home,
  );
  assert.equal(
    second.some((r) => r.profile === "work"),
    false,
  );
  assert.equal(second.filter((r) => r.profile === "personal").length, 1);
  assert.equal(
    await readFile(join(root, "work/demo/SKILL.md"), "utf8"),
    "shared-local",
  );
});

test("removal import preserves non-UTF8 bytes without NUL as base64", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  const bytes = Buffer.from([0xff, 0xfe, 0xfd]);
  await writeFile(join(target, "demo/local.bin"), bytes);
  const receipts = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "import" } },
    agents,
    home,
  );
  const file = receipts[0].localFiles?.find(
    (item) => item.path === "local.bin",
  );
  assert.equal(file?.encoding, "base64");
  assert.deepEqual(Buffer.from(file!.content, "base64"), bytes);
  assert.equal(
    await readFile(join(target, "demo/local.bin")).then((data) =>
      data.equals(bytes),
    ),
    true,
  );
});

test("removal replace archives a changed directory and removes it", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "local");
  const receipts = await synchronize(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  assert.deepEqual(await import("node:fs/promises").then(fs => fs.readdir(join(home, "backups"))).catch(() => []), []);
});

test("changed files are archived before replacement and archive failure preserves them", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-archive-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "local");
  const archived: Array<{skillId:string; files:Array<{path:string;content:string}>; path?:string}> = [];
  const removed = await synchronizeRaw(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
    async payload => { archived.push(payload as typeof archived[number]); },
  );
  assert.equal(removed[0].status, "synchronized");
  assert.equal(archived.length, 1);
  assert.equal(archived[0].skillId, "s1");
  assert.equal(archived[0].files.find(file => file.path === "local.txt")?.content, "local");
  assert.equal(archived[0].path, join(home, "skills/demo"));

  await synchronize(desired([skill("server")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "keep me");
  const missing = await synchronizeRaw(
    { generation: 3, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
  );
  assert.equal(missing[0].status, "failed");
  assert.match(missing[0].message ?? "", /require recovery archiving/);
  assert.equal(await readFile(join(target, "demo/local.txt"), "utf8"), "keep me");

  const failed = await synchronizeRaw(
    { generation: 3, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
    async () => { throw new Error("archive unavailable"); },
  );
  assert.equal(failed[0].status, "failed");
  assert.match(failed[0].message ?? "", /archive unavailable/);
  assert.equal(await readFile(join(target, "demo/local.txt"), "utf8"), "keep me");
});

test("replacement fails safely when changed files contain a nested symlink", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-archive-symlink-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = join(root, "agent"), home = join(root, "state"), external = join(root, "external");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("server")]), agents, home);
  await writeFile(external, "external");
  await symlink(external, join(target, "demo/local-link"));
  let called = false;
  const failed = await synchronizeRaw(
    { generation: 2, skills: [], resolutions: { "s1:codex::": "replace" } },
    agents,
    home,
    async () => { called = true; },
  );
  assert.equal(failed[0].status, "failed");
  assert.match(failed[0].message ?? "", /symbolic link/);
  assert.equal(called, false);
  assert.equal(await readlink(join(target, "demo/local-link")), external);
});

test("target rules are per-device overrides while unspecified agents stay enabled", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const configured = skill("one");
  configured.targets = [
    { deviceId: "device-a", agent: "codex", enabled: false },
  ];
  const receipts = await synchronize(
    desired([configured]),
    [
      { id: "codex", path: join(root, "codex"), deviceId: "device-a" },
      { id: "claude-code", path: join(root, "claude"), deviceId: "device-a" },
    ],
    join(root, "state"),
  );
  assert.deepEqual(
    receipts.map((r) => r.agent),
    ["claude-code"],
  );
  await assert.rejects(readFile(join(root, "codex/demo/SKILL.md")));
  assert.equal(
    await readFile(join(root, "claude/demo/SKILL.md"), "utf8"),
    "one",
  );
});

test("a clean managed skill rename moves ownership to the new folder", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    { generation: 2, skills: [renamed], resolutions: {} },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  assert.equal(await readFile(join(target, "renamed/SKILL.md"), "utf8"), "new");
});

test("a managed skill root migration adopts the duplicate alias across a canonical revision", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-migration-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), join(newRoot, "demo"));
  const receipts = await synchronize(
    { ...desired([skill("two", "r2")]), generation: 2 },
    [{ id: "pi", path: newRoot }],
    home,
  );

  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(lstat(join(oldRoot, "demo")), /ENOENT/);
  assert.equal(await readFile(join(newRoot, "demo/SKILL.md"), "utf8"), "two");
  const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
  const entry = Object.values(ledger.installs)[0] as any;
  assert.equal(entry.path, join(newRoot, "demo"));
  assert.equal(entry.revision, "r2");
});

test("a managed skill root migration ignores generated Python bytecode", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-migration-cache-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  const cache = join(home, "skills/demo/scripts/__pycache__");
  await mkdir(cache);
  await writeFile(join(cache, "run.cpython-313.pyc"), Buffer.from([0, 1, 2]));
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), join(newRoot, "demo"));

  const receipts = await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "synchronized");
  assert.deepEqual(await readFile(join(newRoot, "demo/scripts/__pycache__/run.cpython-313.pyc")), Buffer.from([0, 1, 2]));
  await assert.rejects(lstat(join(oldRoot, "demo")), /ENOENT/);
});

test("a physical alias of the same agent root updates ownership without deleting the destination", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-directory-alias-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), physical = join(root, "physical"), alias = join(root, "alias");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: physical }], home);
  await symlink(physical, alias);

  const receipts = await synchronize(desired([skill("one")]), [{ id: "pi", path: alias }], home);

  assert.equal(receipts[0].status, "synchronized");
  assert.equal(await readFile(join(alias, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(physical, "demo/SKILL.md"), "utf8"), "one");
  const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
  assert.equal((Object.values(ledger.installs)[0] as any).path, join(alias, "demo"));
});

test("a root migration preserves a foreign same-content pointer", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-foreign-pointer-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  const foreign = join(root, "foreign");
  await cp(join(home, "skills/demo"), foreign, { recursive: true });
  await mkdir(newRoot);
  await symlink(foreign, join(newRoot, "demo"));

  const receipts = await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "conflicted");
  assert.match(receipts[0].message ?? "", /already occupied/);
  assert.equal(await realpath(join(newRoot, "demo")), await realpath(foreign));
  assert.equal((await lstat(join(oldRoot, "demo"))).isSymbolicLink(), true);
});

test("a root migration preserves a changed old pointer and a copied installation", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-changed-old-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  const foreign = join(root, "foreign");
  await cp(join(home, "skills/demo"), foreign, { recursive: true });
  await rm(join(oldRoot, "demo"));
  await symlink(foreign, join(oldRoot, "demo"));
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), join(newRoot, "demo"));
  assert.equal((await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home))[0].status, "conflicted");

  await rm(join(oldRoot, "demo"));
  await cp(join(home, "skills/demo"), join(oldRoot, "demo"), { recursive: true });
  const ledger = JSON.parse(await readFile(join(home, "ledger.json"), "utf8"));
  (Object.values(ledger.installs)[0] as any).copied = true;
  await writeFile(join(home, "ledger.json"), JSON.stringify(ledger));
  assert.equal((await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home))[0].status, "conflicted");
});

test("a root migration preserves an indirect old pointer even when it reaches the canonical directory", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-indirect-old-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  const intermediate = join(root, "user-alias");
  await symlink(join(home, "skills/demo"), intermediate);
  await rm(join(oldRoot, "demo"));
  await symlink(intermediate, join(oldRoot, "demo"));
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), join(newRoot, "demo"));

  const receipts = await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readlink(join(oldRoot, "demo")), intermediate);
  assert.equal(await realpath(join(newRoot, "demo")), await realpath(join(home, "skills/demo")));
});

test("a root migration preserves locally modified canonical content", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-modified-canonical-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), join(newRoot, "demo"));
  await writeFile(join(home, "skills/demo/SKILL.md"), "local");

  const receipts = await synchronize(desired([skill("one")]), [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "conflicted");
  assert.equal(await readFile(join(newRoot, "demo/SKILL.md"), "utf8"), "local");
  assert.equal((await lstat(join(oldRoot, "demo"))).isSymbolicLink(), true);
});

test("a managed skill rename preserves a locally modified old folder", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    { generation: 2, skills: [renamed], resolutions: {} },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "conflicted");
  assert.equal(receipts[0].path, join(target, "demo"));
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
  await assert.rejects(readFile(join(target, "renamed/SKILL.md")));
});

test("rename import releases modified old ownership before exclusion", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/SKILL.md"), "local");
  const renamed = skill("new", "r2");
  renamed.name = "renamed";
  const first = await synchronize(
    {
      generation: 2,
      skills: [renamed],
      resolutions: { "s1:codex::": "import" },
    },
    agents,
    home,
  );
  assert.equal(first[0].status, "conflicted");
  assert.equal(
    first[0].localFiles?.find((file) => file.path === "SKILL.md")?.content,
    "local",
  );
  const second = await synchronize(
    { generation: 3, skills: [], resolutions: {} },
    agents,
    home,
  );
  assert.equal(second.length, 0);
  assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "local");
});

test("rename replace archives modified old and occupied new folders", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  await synchronize(desired([skill("old")]), agents, home);
  await writeFile(join(target, "demo/local.txt"), "old-local");
  const fs = await import("node:fs/promises");
  await fs.mkdir(join(target, "renamed"));
  await writeFile(join(target, "renamed/local.txt"), "new-local");
  const renamed = skill("server", "r2");
  renamed.name = "renamed";
  const receipts = await synchronize(
    {
      generation: 2,
      skills: [renamed],
      resolutions: { "s1:codex::": "replace" },
    },
    agents,
    home,
  );
  assert.equal(receipts[0].status, "synchronized");
  await assert.rejects(readFile(join(target, "demo/SKILL.md")));
  assert.equal(
    await readFile(join(target, "renamed/SKILL.md"), "utf8"),
    "server",
  );
  assert.deepEqual(await fs.readdir(join(home, "backups")).catch(() => []), []);
});

test("an unchanged revision leaves the installed directory in place", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-test-"));
  const target = join(root, "agent");
  const home = join(root, "state");
  const agents = [{ id: "codex", path: target }];
  const value = skill("same");
  await synchronize(desired([value]), agents, home);
  const before = await stat(join(target, "demo"));
  await synchronize(
    { generation: 2, skills: [value], resolutions: {} },
    agents,
    home,
  );
  const after = await stat(join(target, "demo"));
  assert.equal(after.ino, before.ino);
  assert.equal(after.mtimeMs, before.mtimeMs);
});

test("an excluded destination retains its installed revision, catches up when re-enabled, and removes on disconnect", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-excluded-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const target = { id: "codex", path: join(root, "agent") };
  const home = join(root, "state");
  await synchronize(desired([skill("one")]), [target], home);
  const excluded = { ...desired([skill("two", "r2")]), generation: 2,
    excludedAgents: [{ agent: "codex" }] };
  assert.deepEqual(await synchronize(excluded, [target], home), []);
  assert.equal(await readFile(join(target.path, "demo/SKILL.md"), "utf8"), "one");
  const retained = await realpath(join(target.path,"demo"));
  assert.match(retained,/retained\/skills\/s1\//);
  assert.deepEqual(await synchronize(excluded, [target], home), []);
  const caughtUp = await synchronize({ ...desired([skill("two", "r2")]), generation: 3 }, [target], home);
  assert.equal(caughtUp[0].status, "synchronized", JSON.stringify(caughtUp[0]));
  assert.equal(await readFile(join(target.path, "demo/SKILL.md"), "utf8"), "two");
  assert.equal(await lstat(retained).catch(()=>null),null);
  await synchronize({ generation: 4, skills: [], resolutions: {} }, [target], home);
  assert.equal(await lstat(join(target.path, "demo")).catch(() => null), null);
});

test("an excluded destination stops following the canonical folder when another agent updates", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-mixed-exclusion-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state");
  const targets = [{ id: "codex", path: join(root, "codex") }, { id: "opencode", path: join(root, "opencode") }, { id: "claude-code", path: join(root, "claude") }];
  await synchronize(desired([skill("one")]), targets, home);
  const next = { ...desired([skill("two", "r2")]), generation: 2, excludedAgents: [{ agent: "codex" },{agent:"opencode"}] };
  await synchronize(next, targets, home);
  assert.equal(await readFile(join(targets[0].path, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await readFile(join(targets[1].path, "demo/SKILL.md"), "utf8"), "one");
  assert.equal(await realpath(join(targets[0].path,"demo")),await realpath(join(targets[1].path,"demo")));
  assert.equal(await readFile(join(targets[2].path, "demo/SKILL.md"), "utf8"), "two");
});

test("shared agent directories remain managed, survive one exclusion, and remove their store after all exclusions", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "equip-shared-ownership-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), path = join(root, "shared");
  const agents = [{ id: "one", path }, { id: "two", path }];
  const value = skill("shared");
  const installed = await synchronize(desired([value]), agents, home);
  assert.ok(installed.every(receipt => receipt.status === "synchronized" && receipt.managed !== false));
  const excluded = { ...value, targets: [{ deviceId: "", agent: "one", enabled: false }] };
  const partial = await synchronize({ ...desired([excluded]), generation: 2 }, agents, home);
  assert.ok(partial.every(receipt => receipt.status === "synchronized"));
  assert.equal(await readFile(join(path, "demo/SKILL.md"), "utf8"), "shared");
  await synchronize({ generation: 3, skills: [], resolutions: {} }, agents, home);
  assert.equal(await lstat(join(path, "demo")).catch(() => null), null);
  assert.equal(await lstat(join(home, "skills/demo")).catch(() => null), null);
});


test("removal preserves a locally substituted symlink even when its contents match", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-removal-link-"));
  const target = join(root, "agent"), home = join(root, "state");
  const targets = [{ id: "codex", path: target }];
  await synchronize(desired([skill("one")]), targets, home);
  await rename(join(target, "demo"), join(root, "local-work"));
  await rm(join(root, "local-work"));
  await symlink(join(home, "skills/demo"), join(root, "local-work"));
  await symlink(join(root, "local-work"), join(target, "demo"));
  const receipts = await synchronize(desired([]), targets, home);
  assert.equal(receipts[0].status, "conflicted");
  assert.equal((await lstat(join(target, "demo"))).isSymbolicLink(), true);
  assert.equal(await readFile(join(root, "local-work/SKILL.md"), "utf8"), "one");
});

test("an update normalizes a managed link chained through another managed destination", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-managed-alias-update-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state");
  const agentsPath = join(root, ".agents/skills");
  const claudePath = join(root, ".claude/skills");
  const targets = [
    { id: "codex", path: agentsPath },
    { id: "claude-code", path: claudePath },
  ];
  await synchronize(desired([skill("one")]), targets, home);
  const intermediate = join(agentsPath, "demo");
  const destination = join(claudePath, "demo");
  const intermediatePointer = await readlink(intermediate);
  await rm(destination);
  await symlink(relative(dirname(destination), intermediate), destination);

  const receipts = await synchronize(desired([skill("two", "r2")]), targets, home);

  assert.ok(receipts.every(receipt => receipt.status === "synchronized"), JSON.stringify(receipts));
  assert.equal(await readlink(intermediate), intermediatePointer, "the intermediate managed alias remains untouched");
  assert.notEqual(await readlink(destination), relative(dirname(destination), intermediate));
  assert.equal(await realpath(destination), await realpath(join(home, "skills/demo")));
  assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "two");
});

test("an update preserves a different physical copy even when it has the desired content", async t => {
  const root = await mkdtemp(join(tmpdir(), "equip-external-copy-update-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), target = join(root, "agent"), destination = join(target, "demo");
  const targets = [{ id: "claude-code", path: target }];
  await synchronize(desired([skill("one")]), targets, home);
  const external = join(root, "external-copy");
  await mkdir(join(external, "scripts"), { recursive: true });
  await writeFile(join(external, "SKILL.md"), "two");
  await writeFile(join(external, "scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
  await rm(destination);
  await symlink(external, destination);

  const receipts = await synchronize(desired([skill("two", "r2")]), targets, home);

  assert.equal(receipts[0].status, "conflicted");
  assert.match(receipts[0].message ?? "", /Managed skill link changed/);
  assert.equal(await realpath(destination), await realpath(external));
  assert.equal(await readFile(join(external, "SKILL.md"), "utf8"), "two");
});

test("removing adopted links removes every managed destination and the unreferenced store", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-observed-canonical-"));
  const home = join(root, "state"), original = join(root, "original"), peer = join(root, "peer");
  await synchronize(desired([skill("one")]), [{ id: "codex", path: join(root, "seed-target") }], join(root, "seed"));
  await cp(join(root, "seed/skills/demo"), join(home, "skills/demo"), { recursive: true });
  await mkdir(original);
  await symlink(join(home, "skills/demo"), join(original, "demo"));
  const linked = skill("one");
  const targets = [{ id: "codex", path: original }, { id: "claude-code", path: peer }];
  assert.ok((await synchronize(desired([linked]), targets, home)).every(r => r.status === "synchronized"));
  await synchronize(desired([]), targets, home);
  await assert.rejects(lstat(join(original, "demo")), /ENOENT/);
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8").catch(() => "removed"), "removed");
  await assert.rejects(lstat(join(peer, "demo")), /ENOENT/);
});

test("a stale failed destination cannot block the next canonical update when another baseline confirms it", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-partial-baseline-"));
  const home = join(root, "state"), targets = [{ id: "codex", path: join(root, "one") }, { id: "claude-code", path: join(root, "two") }];
  await synchronize(desired([skill("one")]), targets, home);
  await rm(join(targets[1].path, "demo"));
  await symlink(join(root, "user-link"), join(targets[1].path, "demo"));
  const second = await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, targets, home);
  assert.deepEqual(second.map(r => r.status), ["synchronized", "conflicted"]);
  const third = await synchronize({ ...desired([skill("three", "r3")]), generation: 3 }, targets, home);
  assert.deepEqual(third.map(r => r.status), ["synchronized", "conflicted"]);
  assert.equal(await readFile(join(home, "skills/demo/SKILL.md"), "utf8"), "three");
});


test("shared agent roots adopt an updated Equip link without changing the original repository", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-central-observed-"));
  const home = join(root, "state"), repository = join(root, "repository"), target = join(root, "agent"), alias = join(root, "alias");
  try {
    await mkdir(join(repository, "demo/scripts"), { recursive: true });
    await writeFile(join(repository, "demo/SKILL.md"), "one");
    await writeFile(join(repository, "demo/scripts/run.sh"), "#!/bin/sh\n", { mode: 0o755 });
    await mkdir(target);
    await symlink(join(repository, "demo"), join(target, "demo"));
    await symlink(target, alias);
    const targets = [{ id: "codex", path: target }, { id: "claude-code", path: alias }];
    assert.ok((await synchronize(desired([skill("one")]), targets, home)).every(r => r.status === "synchronized"));
    const updated = await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, targets, home);
    assert.ok(updated.every(r => r.status === "synchronized"));
    assert.ok(updated.every(r => r.managed !== false));
    assert.equal(await readFile(join(repository, "demo/SKILL.md"), "utf8"), "one");
    assert.equal(await readFile(join(target, "demo/SKILL.md"), "utf8"), "two");
    assert.equal(await readFile(join(alias, "demo/SKILL.md"), "utf8"), "two");
    assert.ok((await synchronize({ ...desired([]), generation: 3 }, targets, home)).every(r => r.status === "synchronized"));
    await assert.rejects(lstat(join(target, "demo")), /ENOENT/);
    assert.equal(await readFile(join(repository, "demo/SKILL.md"), "utf8"), "one");
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("links resolve correctly through agent roots at different physical depths", async () => {
  const root = await mkdtemp(join(tmpdir(), "equip-root-alias-"));
  const physical = join(root, "nested/configuration/skills"), alias = join(root, "agent"), home = join(root, "state");
  try {
    await mkdir(physical, { recursive: true });
    await symlink(physical, alias);
    const target = [{ id: "codex", path: alias }];
    assert.equal((await synchronize(desired([skill("one")]), target, home))[0].status, "synchronized");
    assert.equal(await readFile(join(alias, "demo/SKILL.md"), "utf8"), "one");
    assert.equal((await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, target, home))[0].status, "synchronized");
    assert.equal(await readFile(join(physical, "demo/SKILL.md"), "utf8"), "two");
    assert.equal((await synchronize({ ...desired([]), generation: 3 }, target, home))[0].status, "synchronized");
    await assert.rejects(lstat(join(physical, "demo")), /ENOENT/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

// Windows renames with MoveFileExW, which refuses an existing directory
// destination; managed links there are junctions, so they count as directories.
async function watchRenames(
  t: import("node:test").TestContext,
  platform: NodeJS.Platform,
  fail: (from: string, to: string) => boolean = () => false,
) {
  const descriptor = Object.getOwnPropertyDescriptor(process, "platform")!;
  Object.defineProperty(process, "platform", { ...descriptor, value: platform });
  const realRename = fsPromises.rename;
  const renames: Array<[string, string]> = [];
  t.mock.method(fsPromises, "rename", async (from: string, to: string) => {
    renames.push([String(from), String(to)]);
    if (platform === "win32" && (await stat(to).catch(() => null))?.isDirectory())
      throw Object.assign(new Error(`EPERM: operation not permitted, rename '${from}' -> '${to}'`), { code: "EPERM" });
    if (fail(String(from), String(to)))
      throw Object.assign(new Error(`EBUSY: resource busy or locked, rename '${from}' -> '${to}'`), { code: "EBUSY" });
    return realRename(from, to);
  });
  syncBuiltinESMExports();
  t.after(() => {
    Object.defineProperty(process, "platform", descriptor);
    t.mock.restoreAll();
    syncBuiltinESMExports();
  });
  return renames;
}

async function equipLeftovers(...dirs: string[]) {
  const names = await Promise.all(dirs.map(dir => readdir(dir)));
  return names.flat().filter(name => name.includes(".equip-"));
}

async function chainedAlias(prefix: string) {
  const root = await realpath(await mkdtemp(join(tmpdir(), prefix)));
  const home = join(root, "state");
  const agentsPath = join(root, ".agents/skills"), claudePath = join(root, ".claude/skills");
  const targets = [{ id: "codex", path: agentsPath }, { id: "claude-code", path: claudePath }];
  return { root, home, agentsPath, claudePath, targets,
    intermediate: join(agentsPath, "demo"), destination: join(claudePath, "demo") };
}

test("on Windows a root migration replaces the duplicate alias junction through the transaction journal", async t => {
  const root = await realpath(await mkdtemp(join(tmpdir(), "equip-win-root-migration-")));
  t.after(() => rm(root, { recursive: true, force: true }));
  const renames = await watchRenames(t, "win32");
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  const destination = join(newRoot, "demo");
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  await mkdir(newRoot);
  await symlink(join(home, "skills/demo"), destination, "junction");

  const receipts = await synchronize({ ...desired([skill("two", "r2")]), generation: 2 }, [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "synchronized", JSON.stringify(receipts));
  assert.ok(renames.some(([from, to]) => from === destination && to.startsWith(`${destination}.equip-old-`)));
  assert.equal(await readFile(join(destination, "SKILL.md"), "utf8"), "two");
  await assert.rejects(lstat(join(oldRoot, "demo")), /ENOENT/);
  assert.deepEqual(await equipLeftovers(oldRoot, newRoot), []);
  await assert.rejects(lstat(join(home, "transaction.json")), /ENOENT/);
  const entry = Object.values(JSON.parse(await readFile(join(home, "ledger.json"), "utf8")).installs)[0] as any;
  assert.equal(entry.path, destination);
  assert.equal(entry.revision, "r2");
});

test("on Windows recovery removes the old root when a root migration stops after its ledger commit", async t => {
  const root = await realpath(await mkdtemp(join(tmpdir(), "equip-win-root-crash-")));
  t.after(() => rm(root, { recursive: true, force: true }));
  const home = join(root, "state"), oldRoot = join(root, "old"), newRoot = join(root, "new");
  const obsolete = join(oldRoot, "demo"), store = join(home, "skills/demo");
  let journalAtCommit: string | undefined;
  await watchRenames(t, "win32", (_from, to) => {
    if (to === join(home, "ledger.json") && existsSync(join(home, "transaction.json")))
      journalAtCommit = readFileSync(join(home, "transaction.json"), "utf8");
    return false;
  });
  await synchronize(desired([skill("one")]), [{ id: "pi", path: oldRoot }], home);
  await mkdir(newRoot);
  await symlink(store, join(newRoot, "demo"), "junction");
  const next = { ...desired([skill("two", "r2")]), generation: 2 };
  assert.equal((await synchronize(next, [{ id: "pi", path: newRoot }], home))[0].status, "synchronized");

  // Recreate the state of a pass that stopped right after the ledger commit.
  assert.ok(journalAtCommit);
  await writeFile(join(home, "transaction.json"), journalAtCommit);
  await symlink(store, obsolete, "junction");
  await symlink(store, JSON.parse(journalAtCommit).oldPath, "junction");

  const receipts = await synchronize(next, [{ id: "pi", path: newRoot }], home);

  assert.equal(receipts[0].status, "synchronized", JSON.stringify(receipts));
  await assert.rejects(lstat(obsolete), /ENOENT/);
  assert.deepEqual(await equipLeftovers(oldRoot, newRoot), []);
  await assert.rejects(lstat(join(home, "transaction.json")), /ENOENT/);
  assert.equal(await readFile(join(newRoot, "demo/SKILL.md"), "utf8"), "two");
});

test("on Windows an update normalizes a chained managed junction through the transaction journal", async t => {
  const fixture = await chainedAlias("equip-win-alias-update-");
  t.after(() => rm(fixture.root, { recursive: true, force: true }));
  const renames = await watchRenames(t, "win32");
  await synchronize(desired([skill("one")]), fixture.targets, fixture.home);
  await rm(fixture.destination);
  await symlink(fixture.intermediate, fixture.destination, "junction");

  const receipts = await synchronize(desired([skill("two", "r2")]), fixture.targets, fixture.home);

  assert.ok(receipts.every(receipt => receipt.status === "synchronized"), JSON.stringify(receipts));
  assert.ok(renames.some(([from, to]) => from === fixture.destination && to.startsWith(`${fixture.destination}.equip-old-`)));
  assert.equal(await readlink(fixture.destination), join(fixture.home, "skills/demo"));
  assert.equal(await readFile(join(fixture.destination, "SKILL.md"), "utf8"), "two");
  assert.deepEqual(await equipLeftovers(fixture.agentsPath, fixture.claudePath), []);
  await assert.rejects(lstat(join(fixture.home, "transaction.json")), /ENOENT/);
});

test("on Windows a re-enabled excluded destination moves its retained junction aside", async t => {
  const root = await realpath(await mkdtemp(join(tmpdir(), "equip-win-excluded-")));
  t.after(() => rm(root, { recursive: true, force: true }));
  await watchRenames(t, "win32");
  const target = { id: "codex", path: join(root, "agent") }, home = join(root, "state");
  await synchronize(desired([skill("one")]), [target], home);
  await synchronize({ ...desired([skill("two", "r2")]), generation: 2, excludedAgents: [{ agent: "codex" }] }, [target], home);
  assert.match(await realpath(join(target.path, "demo")), /retained/);

  const caughtUp = await synchronize({ ...desired([skill("two", "r2")]), generation: 3 }, [target], home);

  assert.equal(caughtUp[0].status, "synchronized", JSON.stringify(caughtUp));
  assert.equal(await readlink(join(target.path, "demo")), join(home, "skills/demo"));
  assert.equal(await readFile(join(target.path, "demo/SKILL.md"), "utf8"), "two");
  assert.deepEqual(await equipLeftovers(target.path), []);
});

for (const restoreFails of [false, true])
  test(`on Windows a failed junction promotion restores the original link${restoreFails ? " through journal recovery" : ""}`, async t => {
    const fixture = await chainedAlias("equip-win-alias-failure-");
    t.after(() => rm(fixture.root, { recursive: true, force: true }));
    let failures = 0;
    await watchRenames(t, "win32", (from, to) => to === fixture.destination && failures > 0 &&
      (from.includes(".equip-stage-") || from.includes(".equip-old-")) && failures-- > 0);
    await synchronize(desired([skill("one")]), fixture.targets, fixture.home);
    await rm(fixture.destination);
    await symlink(fixture.intermediate, fixture.destination, "junction");
    failures = restoreFails ? 2 : 1;

    const receipts = await synchronize(desired([skill("two", "r2")]), fixture.targets, fixture.home);

    assert.equal(failures, 0);
    const failed = receipts.find(receipt => receipt.agent === "claude-code");
    assert.equal(failed?.status, "failed", JSON.stringify(receipts));
    assert.match(failed?.message ?? "", /EBUSY/);
    assert.equal(await readlink(fixture.destination), fixture.intermediate, "the original link is restored");
    assert.deepEqual(await equipLeftovers(fixture.agentsPath, fixture.claudePath), []);
    await assert.rejects(lstat(join(fixture.home, "transaction.json")), /ENOENT/);
    const retried = await synchronize(desired([skill("two", "r2")]), fixture.targets, fixture.home);
    assert.ok(retried.every(receipt => receipt.status === "synchronized"), JSON.stringify(retried));
    assert.equal(await readlink(fixture.destination), join(fixture.home, "skills/demo"));
  });

test("on POSIX a managed link replacement stays a single atomic rename", async t => {
  const fixture = await chainedAlias("equip-posix-alias-update-");
  t.after(() => rm(fixture.root, { recursive: true, force: true }));
  const renames = await watchRenames(t, "linux");
  await synchronize(desired([skill("one")]), fixture.targets, fixture.home);
  await rm(fixture.destination);
  await symlink(relative(dirname(fixture.destination), fixture.intermediate), fixture.destination);
  renames.length = 0;

  const receipts = await synchronize(desired([skill("two", "r2")]), fixture.targets, fixture.home);

  assert.ok(receipts.every(receipt => receipt.status === "synchronized"), JSON.stringify(receipts));
  assert.ok(renames.some(([from, to]) => from.startsWith(`${fixture.destination}.equip-stage-`) && to === fixture.destination));
  assert.ok(!renames.some(([, to]) => to.startsWith(`${fixture.destination}.equip-old-`)), JSON.stringify(renames));
  assert.equal(await realpath(fixture.destination), await realpath(join(fixture.home, "skills/demo")));
});
